export interface Teacher {
    slug: string;
    name: string;
    position: string;
    department: string;
    image: string;
    designation: string;
    qualifications: string;
    specialization?: string[];
    courses?: string[];
    researchInterests?: string[];
    achievements?: string[];
}

export const facultyData: Record<string, Teacher[]> = {
    Principal: [
        {
            slug: "idrees-ahmed",
            name: "Prof. Idrees Ahmed",
            position: "Principal / Professor BPS-20",
            department: "Mathematics Department",
            image: "/Images/faculty/idrees-ahmed.jpeg",
            designation: "Principal / Professor",
            qualifications: "M.Sc. Mathematics",
            specialization: ["Mathematics", "Academic Administration"],
            courses: ["Calculus", "Linear Algebra"],
            researchInterests: ["Educational Management"],
            achievements: ["Certified Educational Leader"],
        },
    ],

    "Associate Professor": [
        {
            slug: "ghulam-akbar",
            name: "Ghulam Akbar",
            position: "Vice Principal / Associate Professor BPS-19",
            department: "Statistics Department",
            image: "/Images/faculty/ghulam-akbar.jpeg",
            designation: "Vice Principal / Associate Professor",
            qualifications: "M.Sc. Statistics",
            specialization: ["Statistical Inference", "Probability"],
            courses: ["Basic Statistics", "Advanced Statistics"],
            researchInterests: ["Data Analysis"],
            achievements: ["Best Teacher Award 2023"],
        },
        {
            slug: "shariq-zuberi",
            name: "Shariq Zuberi",
            position: "Associate Professor BPS-19",
            department: "Statistics Department",
            image: "/Images/faculty/shariq-zuberi.jpeg",
            designation: "Associate Professor",
            qualifications: "M.Sc. Statistics",
            specialization: ["Applied Statistics"],
            courses: ["Probability Theory", "Sampling Techniques"],
            researchInterests: ["Demography"],
            achievements: ["Senior Research Fellow"],
        },
        {
            slug: "bushra-shaikh",
            name: "Bushra Shaikh",
            position: "Associate Professor BPS-19",
            department: "English Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Associate Professor",
            qualifications: "M.A. English",
            specialization: ["English Literature"],
            courses: ["Communication Skills", "English Literature"],
            researchInterests: ["Post-colonial Literature"],
            achievements: ["Distinguished Faculty Member"],
        },
        {
            slug: "durdana",
            name: "Durdana",
            position: "Associate Professor BPS-19",
            department: "Urdu Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Associate Professor",
            qualifications: "M.A. Urdu",
            specialization: ["Urdu Poetry"],
            courses: ["Urdu Literature", "Linguistics"],
            researchInterests: ["Urdu Ghazal"],
            achievements: ["Literary Contribution Award"],
        },
        {
            slug: "rozina-naz",
            name: "Rozina Naz",
            position: "Associate Professor BPS-19",
            department: "Physics Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Associate Professor",
            qualifications: "M.Sc. Physics",
            specialization: ["Quantum Mechanics"],
            courses: ["Nuclear Physics", "Modern Physics"],
            researchInterests: ["Theoretical Physics"],
            achievements: ["Research Excellence Award"],
        },
        {
            slug: "nasima-shaheen",
            name: "Nasima Shaheen",
            position: "Associate Professor BPS-19",
            department: "Chemistry Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Associate Professor",
            qualifications: "M.Sc. Chemistry",
            specialization: ["Organic Chemistry"],
            courses: ["Biochemistry", "Analytical Chemistry"],
            researchInterests: ["Medicinal Chemistry"],
            achievements: ["Chemistry Research Grant"],
        },
    ],

    "Assistant Professor": [
        {
            slug: "dr-faheem",
            name: "Dr. Muhammad Faheem",
            position: "Assistant Professor",
            department: "Zoology Department",
            image: "/Images/faculty/dr-faheem.jpeg",
            designation: "Assistant Professor",
            qualifications: "Ph.D. Zoology",
            specialization: ["Marine Biology", "Ecology"],
            courses: ["Animal Diversity", "Environmental Science"],
            researchInterests: ["Conservation Biology"],
            achievements: ["Ph.D. Research Award"],
        },
        {
            slug: "ambreen-akbar",
            name: "Ambreen Akbar",
            position: "Assistant Professor",
            department: "Computer Science Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Assistant Professor",
            qualifications: "MS Computer Science",
            specialization: ["Software Engineering"],
            courses: ["Programming Fundamentals", "Database Systems"],
            researchInterests: ["Software Quality Assurance"],
            achievements: ["IT Specialist Certification"],
        },
        {
            slug: "shehlaa-amjad",
            name: "Shehla Amjad",
            position: "Assistant Professor",
            department: "Chemistry Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Assistant Professor",
            qualifications: "M.Sc. Chemistry",
            specialization: ["Inorganic Chemistry"],
            courses: ["Physical Chemistry", "General Chemistry"],
            researchInterests: ["Catalysis"],
            achievements: ["Lab Management Excellence"],
        },
        {
            slug: "shabana-malik",
            name: "Shabana Malik",
            position: "Assistant Professor",
            department: "English Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Assistant Professor",
            qualifications: "M.A. English",
            specialization: ["TESL", "Linguistics"],
            courses: ["Grammar & Composition", "Functional English"],
            researchInterests: ["Applied Linguistics"],
            achievements: ["Student Mentor Award"],
        },
        {
            slug: "hiba-haq",
            name: "Hiba Haq",
            position: "Assistant Professor",
            department: "Physics Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Assistant Professor",
            qualifications: "M.Sc. Physics",
            specialization: ["Electronics"],
            courses: ["Electromagnetism", "Optics"],
            researchInterests: ["Solid State Physics"],
            achievements: ["Physics Lab Innovator"],
        },
    ],

    Lecturer: [
        {
            slug: "marvi-bhutto",
            name: "Marvi Bhutto",
            position: "Lecturer",
            department: "Urdu Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.A. Urdu",
            specialization: ["Urdu Prose"],
            courses: ["Compulsory Urdu"],
            researchInterests: ["Modern Urdu Literature"],
            achievements: ["Creative Writing Award"],
        },
        {
            slug: "eidal-khan",
            name: "Eidal Khan",
            position: "Lecturer",
            department: "Chemistry Department",
            image: "/Images/faculty/eidal-khan.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Chemistry",
            specialization: ["Physical Chemistry"],
            courses: ["Introductory Chemistry"],
            researchInterests: ["Material Science"],
            achievements: ["Outstanding Junior Faculty"],
        },
        {
            slug: "shafique-ahmed",
            name: "Shafique Ahmed",
            position: "Lecturer",
            department: "Botany Department",
            image: "/Images/faculty/shafique-ahmed.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Botany",
            specialization: ["Plant Physiology"],
            courses: ["General Botany"],
            researchInterests: ["Plant Pathology"],
            achievements: ["Botanical Garden Supervisor"],
        },
        {
            slug: "erum-abbas",
            name: "Erum Abbas",
            position: "Lecturer",
            department: "Urdu Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.A. Urdu",
            specialization: ["Urdu Translation"],
            courses: ["Basic Urdu"],
            researchInterests: ["Classical Urdu Literature"],
            achievements: ["Translation Excellence"],
        },
        {
            slug: "sana-ishrat",
            name: "Sana Ishrat",
            position: "Lecturer",
            department: "Physics Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Physics",
            specialization: ["Astrophysics"],
            courses: ["Introductory Physics"],
            researchInterests: ["Space Science"],
            achievements: ["Space Science Workshop Leader"],
        },
        {
            slug: "usman-ali-mangrio",
            name: "Usman Ali Mangrio",
            position: "Lecturer",
            department: "Accounts Department",
            image: "/Images/faculty/usman-ali-mangrio.jpeg",
            designation: "Lecturer",
            qualifications: "M.Com",
            specialization: ["Accounting", "Finance"],
            courses: ["Financial Accounting", "Principles of Accounting"],
            researchInterests: ["SME Finance"],
            achievements: ["Certified Accountant"],
        },
        {
            slug: "tashkeel-ahmed",
            name: "Tashkeel Ahmed",
            position: "Lecturer",
            department: "Pak-Studies Department",
            image: "/Images/faculty/tashkeel-ahmed.jpeg",
            designation: "Lecturer",
            qualifications: "M.A. Pak Studies",
            specialization: ["History of Pakistan"],
            courses: ["Pak-Studies Compulsory"],
            researchInterests: ["Political History"],
            achievements: ["History Seminar Coordinator"],
        },
        {
            slug: "laraib",
            name: "Laraib",
            position: "Lecturer",
            department: "Maths Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Mathematics",
            specialization: ["Discrete Mathematics"],
            courses: ["General Mathematics"],
            researchInterests: ["Graph Theory"],
            achievements: ["Mathematical Olympiad Mentor"],
        },
        {
            slug: "syed-salman-ali",
            name: "Syed Salman Ali",
            position: "Lecturer",
            department: "Commerce Department",
            image: "/Images/faculty/syed-salman-ali.jpeg",
            designation: "Lecturer",
            qualifications: "MBA Commerce",
            specialization: ["Marketing"],
            courses: ["Business Studies"],
            researchInterests: ["E-commerce"],
            achievements: ["Business Coach"],
        },
        {
            slug: "ali-imran",
            name: "Ali Imran",
            position: "Lecturer",
            department: "Islamiat Department",
            image: "/Images/faculty/ali-imran.jpeg",
            designation: "Lecturer",
            qualifications: "M.A. Islamic Studies",
            specialization: ["Islamic Jurisprudence"],
            courses: ["Islamiat Compulsory"],
            researchInterests: ["Islamic History"],
            achievements: ["Religious Scholar"],
        },
        {
            slug: "aqsa-rao",
            name: "Aqsa Rao",
            position: "Lecturer",
            department: "Commerce Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.Com",
            specialization: ["Business Law"],
            courses: ["Principles of Commerce"],
            researchInterests: ["Consumer Behavior"],
            achievements: ["Commerce Club Organizer"],
        },
        {
            slug: "alishbah-khan",
            name: "Alishbah Khan",
            position: "Lecturer",
            department: "Computer Science Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "BS Computer Science",
            specialization: ["Web Development"],
            courses: ["Introduction to IT"],
            researchInterests: ["Machine Learning"],
            achievements: ["Full Stack Developer"],
        },
        {
            slug: "syed-ahsan-kamal",
            name: "Syed Ahsan Kamal",
            position: "Lecturer",
            department: "Maths Department",
            image: "/Images/faculty/syed-ahsan-kamal.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Mathematics",
            specialization: ["Analytical Geometry"],
            courses: ["Algebra & Trigonometry"],
            researchInterests: ["Number Theory"],
            achievements: ["Math Workshop Facilitator"],
        },
        {
            slug: "m-asfandyar-anssari",
            name: "M. Asfandyar Anssari",
            position: "Lecturer",
            department: "Chemistry Department",
            image: "/Images/faculty/m-asfandyar-anssari.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Chemistry",
            specialization: ["Industrial Chemistry"],
            courses: ["Inorganic Chemistry"],
            researchInterests: ["Environmental Chemistry"],
            achievements: ["Lab Safety Officer"],
        },
        {
            slug: "mudassir-siddiqui",
            name: "Mudassir Siddiqui",
            position: "Lecturer",
            department: "English Department",
            image: "/Images/faculty/mudassir-siddiqui.jpeg",
            designation: "Lecturer",
            qualifications: "M.A. English",
            specialization: ["English Phonology"],
            courses: ["Spoken English"],
            researchInterests: ["Modern Drama"],
            achievements: ["Drama Club President"],
        },
        {
            slug: "samra-sibtain",
            name: "Samra Sibtain",
            position: "Lecturer",
            department: "Physics Department",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Physics",
            specialization: ["Classical Mechanics"],
            courses: ["Kinematics"],
            researchInterests: ["Waves and Oscillations"],
            achievements: ["Physics Demonstrator"],
        },
        {
            slug: "shujaat-hussain",
            name: "Shujaat Hussain",
            position: "Lecturer",
            department: "Economics Department",
            image: "/Images/faculty/shujaat-hussain.jpeg",
            designation: "Lecturer",
            qualifications: "M.Sc. Economics",
            specialization: ["Microeconomics"],
            courses: ["Principles of Economics"],
            researchInterests: ["Global Markets"],
            achievements: ["Economics Forum Member"],
        },
        {
            slug: "syed-younus",
            name: "Syed Younus",
            position: "Honorary-Lecturer",
            department: "Islamiat Department",
            image: "/Images/faculty/syed-younus.jpeg",
            designation: "Honorary-Lecturer",
            qualifications: "Senior Scholar",
            specialization: ["Religious Education"],
            courses: ["Advanced Islamic Studies"],
            researchInterests: ["Theology"],
            achievements: ["Community Recognition Award"],
        },
    ],
    "Non-Teaching Staff": [
        {
            slug: "ayaz-ali",
            name: "Ayaz Ali",
            position: "Sr. Clerk",
            department: "Admin Office",
            image: "/Images/faculty/non-teaching/ayaz-ali.jpeg",
            designation: "Sr. Clerk",
            qualifications: "Bachelor",
            specialization: ["Administration"],
            courses: [],
            researchInterests: [],
            achievements: ["Seniority Recognition"],
        },
        {
            slug: "mehjabeen",
            name: "Mehjabeen",
            position: "Lab. Sup.",
            department: "Lab. Physics",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lab. Sup.",
            qualifications: "Graduate",
            specialization: ["Physics Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: ["Lab Management"],
        },
        {
            slug: "shahana-mehar",
            name: "Shahana Mehar",
            position: "Lab. Sup.",
            department: "Lab. Physics",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Lab. Sup.",
            qualifications: "Graduate",
            specialization: ["Physics Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: ["Lab Setup Specialist"],
        },
        {
            slug: "sahib-d-lashari",
            name: "Sahib D. Lashari",
            position: "Jr. Clerk",
            department: "Admin Office",
            image: "/Images/faculty/non-teaching/sahib-d-lashari.jpeg",
            designation: "Jr. Clerk",
            qualifications: "Inter",
            specialization: ["Record Keeping"],
            courses: [],
            researchInterests: [],
            achievements: ["Error-free Admin Award"],
        },
        {
            slug: "hassan-ali-jakhio",
            name: "Hassan Ali Jakhio",
            position: "Jr. Clerk",
            department: "Admin Office",
            image: "/Images/faculty/non-teaching/hassan-ali-jakhio.jpeg",
            designation: "Jr. Clerk",
            qualifications: "Inter",
            specialization: ["Support Staff"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "shagufta-jumani",
            name: "Shagufta Jumani",
            position: "Sr. Lab. Asstt",
            department: "Lab. Zoology",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Sr. Lab. Asstt",
            qualifications: "B.Sc.",
            specialization: ["Zoology Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "zoya-jumani",
            name: "Zoya Jumani",
            position: "Sr. Lab. Asstt",
            department: "Lab. Computer",
            image: "/Images/faculty/female-staff.jpeg",
            designation: "Sr. Lab. Asstt",
            qualifications: "B.Sc.",
            specialization: ["Computer Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "m-rashid-khan",
            name: "M. Rashid Khan",
            position: "Sr. Lab. Asstt",
            department: "Lab. Chemistry",
            image: "/Images/faculty/non-teaching/m-rashid-khan.jpeg",
            designation: "Sr. Lab. Asstt",
            qualifications: "B.Sc.",
            specialization: ["Chemistry Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "anwar-hussain",
            name: "Anwar Hussain",
            position: "Lab. Atted",
            department: "Library",
            image: "/Images/faculty/non-teaching/anwar-hussain.jpeg",
            designation: "Lab. Atted",
            qualifications: "Matric",
            specialization: ["Library Assistant"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "syed-amjad-ali-shah",
            name: "Syed Amjad Ali Shah",
            position: "Lab. Atted",
            department: "Principal Office",
            image: "/Images/faculty/non-teaching/syed-amjad-ali-shah.jpeg",
            designation: "Lab. Atted",
            qualifications: "Matric",
            specialization: ["Office Support"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "rahim-bux",
            name: "Rahim Bux",
            position: "Lab. Atted",
            department: "Principal Office",
            image: "/Images/faculty/non-teaching/rahim-bux.jpeg",
            designation: "Lab. Atted",
            qualifications: "Matric",
            specialization: ["Office Support"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "s-m-imran",
            name: "S. M. Imran",
            position: "Lab. Atted",
            department: "Lab. Botany",
            image: "/Images/faculty/non-teaching/s-m-imran.jpeg",
            designation: "Lab. Atted",
            qualifications: "Matric",
            specialization: ["Botany Laboratory"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "m-kamran",
            name: "M. Kamran",
            position: "Chowkidar",
            department: "College Main Gate",
            image: "/Images/faculty/non-teaching/m-kamran.jpeg",
            designation: "Chowkidar",
            qualifications: "-",
            specialization: ["Security"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "asif-mujtaba",
            name: "Asif Mujtaba",
            position: "Chowkidar",
            department: "College Main Gate",
            image: "/Images/faculty/non-teaching/asif-mujtaba.jpeg",
            designation: "Chowkidar",
            qualifications: "-",
            specialization: ["Security"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "ali-asghar",
            name: "Ali Asghar",
            position: "Chowkidar",
            department: "Admin Office",
            image: "/Images/faculty/non-teaching/ali-asghar.jpeg",
            designation: "Chowkidar",
            qualifications: "-",
            specialization: ["Security"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "ali-akbar",
            name: "Ali Akbar",
            position: "Mai",
            department: "Garden",
            image: "/Images/faculty/non-teaching/ali-akbar.jpeg",
            designation: "Gardener",
            qualifications: "-",
            specialization: ["Gardening"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
        {
            slug: "nazar-masih",
            name: "Nazar Masih",
            position: "Sweeper",
            department: "Cleaning",
            image: "/Images/faculty/non-teaching/nazar-masih.jpeg",
            designation: "Sanitary Worker",
            qualifications: "-",
            specialization: ["Cleaning"],
            courses: [],
            researchInterests: [],
            achievements: [],
        },
    ],
};

// Flatten the data for easier access by slug
export const teachers = Object.values(facultyData).flat();
